repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # You can change this to the latest version if needed
    hooks:
      - id: black
        name: black
        language_version: python3.10  # Adjust this to your Python version

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100]  # Set to 100 or any preferred value

  - repo: local
    hooks:
      - id: comment-check
        name: Comment Check
        entry: python comment_check.py  # Use your custom script for checking comments
        language: python
        types: [python]

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10'  # Replace with a specific version (e.g., v1.7.0)
    hooks:
      - id: bandit
        name: Bandit Security Linter
        description: "Bandit finds common security issues in Python code."
        entry: bandit
        language: python
        types: [python]

repos:
  - repo: local  # Indicates a local script
    hooks:
      - id: merge-conflict-check
        name: Merge Conflict Check
        entry: python check_merge_conflicts.py  # Path to your script
        language: python
        types: [python]  

repos:
  - repo: local
    hooks:
      - id: large-file-check
        name: Large File Check
        entry: python check_large_file.py
        language: python
        types: [file]  # This ensures it runs on all file types
